### ISSUE TITLE
get kicked when another player join the server

### ISSUE THREAD

**Issue by hakmhussen** [radistmorse/PEPatch#7]
every time my friend join the server he gets me disconnected and the same goes for him if i join in when he already in the server 
we are have a LAN server using hamachi cuz i cant port forward my connection

**Comment by radistmorse** [comment]
That's probably caused by IDs collision. First of all make sure you're using the latest version. There is one in 13 million chance of collision, so if the version is latest, congratulation, you just won a lottery :). There are two ways to change an ID. First: change name of your character. That will change an ID as well. Second, you can force the ID by putting it in the player filter input in the lobby screen. Any number will do, as long as it's smaller than 13 million. But you have to remember it then, and put it in every time you connect.

**Comment by hakmhussen** [comment]
ok thnx
